services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.08-py3
    container_name: quality-assurance-triton
    command:
      - tritonserver
      - --model-repository=/models
      - --strict-model-config=false
      - --log-verbose=0
      - --http-port=9000
    ports:
      - "9000:9000"
    volumes:
      - ./model_repository:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
